### ISSUE TITLE
Trim path from filename when generating env name

### ISSUE THREAD

**Issue by mkb** [genesis-community/genesis#349]
If I `genesis do ./snw-mkb-lab.yml login` then the director shows up in `bosh envs` with the `./` at the beginning of the name.

**Comment by jhunt** [comment]
I'm curious what happens if you do something pathological like `genesis do $PWD/snw-mkb-lab.yml login`; IIRC, all Genesis does is trim off the `.yml`, as a courtesy to tab-completers (who aren't using paths with directories in them).

Rather than trim paths off, I'd be inclined (in this and similar cases) to push back on "cleaning up" the path for the user.  As @dennisjbell mentioned in the Slack conversation, the argument to `genesis do` is an environment _name_, not a path to a file.

**Comment by dennisjbell** [comment]
Genesis v2.7.0 adds a convenience factor of specifying the env file as part of the -C argument,  for those that want to specify a full path:

```
genesis -C ../bosh/c-aws-uswest1.yml do -- login
```

is the shorthand equivalent of 

```
genesis -C ../bosh do c-aws-uswest1 -- login
```

**Comment by dennisjbell** [comment]
however, I do think that ./snw-mkb-lab.yml is NOT a valid environment name and should have been rejected.
