### ISSUE TITLE
Pipeline email notifications not implemented

### ISSUE THREAD

**Issue by a2geek** [genesis-community/genesis#461]
When I setup email notifications in a pipeline, Genesis responds with this error:
```
$ genesis repipe

Verifying availability of vault 'gdc-prod' (https://192.168.124.12)...ok

ERRORS encountered in pipeline definition in ci.yml:
  - Email notifications are not fully implemented yet.
```

As an experiment, I commented out the `to` and `from` (just to verify the yaml is correct-ish):
```
$ genesis repipe

Verifying availability of vault 'gdc-prod' (https://192.168.124.12)...ok

ERRORS encountered in pipeline definition in ci.yml:
  - Email notifications are not fully implemented yet.
  - `pipeline.email.to' is required.
  - `pipeline.email.from' is required.
```

This suggests that the yaml is correct.

Version:
```
$ genesis --version
Genesis v2.7.33 (fbcde6230e) build 20210615.063959
```

In case this matters, this deployment is using the generic kit: 
```
kit:
  name:     generic
  version:  1.0.0
```

**Comment by a2geek** [comment]
Maybe not? :joy: 
https://github.com/genesis-community/genesis/blob/851905f23c630c24600853a8fb0a0b32ca725882/lib/Genesis/CI/Legacy.pm#L277-L278

**Comment by mrferris** [comment]
As you've found, the pipeline email notification feature is not yet fully implemented. 
This is due to virtually all enterprise users of Genesis wanting Slack or Shout notifications rather than email. 

We don't currently have a spot in our near-term roadmap for implementing email, though we do accept pull requests and would be happy to review one that fully implements email notifications.

**Comment by a2geek** [comment]
I actually found that setting up a personal slack channel was more than sufficient. Closing this one out. Thanks!
